version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    # Look for `requirements.txt` in the `root` directory
    directory: "/"
    # Check the PyPI registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          dependency_name: "recipe-scrapers"

